# Generated by Django 3.0.5 on 2020-04-27 14:13

from django.db import migrations, models
import dob_rest_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dob_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phoneNo',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, validators=[dob_rest_api.validators.name_validator]),
        ),
    ]
