# Generated by Django 3.0.5 on 2020-04-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dob_rest_api', '0002_auto_20200427_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phoneNo',
        ),
    ]
